Part 1 - Numpy

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [15]:
import numpy as np
import urllib.request
import ssl

# Create an SSL context that ignores certificate verification
context = ssl._create_unverified_context()

# URL of the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Download the file and read its contents
response = urllib.request.urlopen(url, context=context)
data = response.read().decode("utf-8").splitlines()

# Convert to NumPy array
iris_2d = np.genfromtxt(data, delimiter=",", dtype=float, usecols=[0,1,2,3])

In [16]:
A = iris_2d[1:4]
B = iris_2d[6:9]
print(A)
print(B)
C = np.vstack((A,B))
D = np.hstack((A,B))
print(C)
print(D)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[[4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]
[[4.9 3.  1.4 0.2 4.6 3.4 1.4 0.3]
 [4.7 3.2 1.3 0.2 5.  3.4 1.5 0.2]
 [4.6 3.1 1.5 0.2 4.4 2.9 1.4 0.2]]


In [18]:
intersection_set = np.intersect1d(A,B)
print(intersection_set)

[0.2 1.4 1.5 4.6]


In [23]:
print(A[np.where((A < 5) & (A > 3))])

[4.9 4.7 3.2 4.6 3.1]


In [25]:
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Part 2 - Pandas

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [ ]:
import pandas as pd

# Fetch data from the URL
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
response = urllib.request.urlopen(url, context=context)

# Convert response to a pandas DataFrame
df = pd.read_csv(response)

print(df.head())  # Print first few rows


   Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura     Integra    Small       12.9   15.9       18.8      25.0   
1           NaN      Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi          90  Compact       25.9   29.1       32.3      20.0   
3          Audi         100  Midsize        NaN   37.7       44.6      19.0   
4           BMW        535i  Midsize        NaN   30.0        NaN      22.0   
5         Buick     Century  Midsize       14.2   15.7       17.3      22.0   
6         Buick     LeSabre    Large       19.9   20.8        NaN      19.0   
7         Buick  Roadmaster    Large       22.6   23.7       24.9      16.0   
8         Buick     Riviera  Midsize       26.3   26.3       26.3      19.0   
9      Cadillac     DeVille    Large       33.0   34.7       36.3      16.0   
10     Cadillac     Seville  Midsize       37.5   40.1       42.7      16.0   
11    Chevrolet    Cavalier  Compact        8.5   13

In [44]:
filter_rows = df[['Manufacturer','Model','Type']][0::19]
print(filter_rows)

     Manufacturer       Model     Type
0           Acura     Integra    Small
19            NaN    Concorde    Large
38            Geo       Metro    Small
57  Mercedes-Benz        190E  Compact
76        Pontiac  Bonneville    Large


In [45]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
response = urllib.request.urlopen(url, context=context)

# Convert response to a pandas DataFrame
df = pd.read_csv(response)

print(df.head())

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0     

In [51]:
avg_min_price = np.mean(df['Min.Price'])
print(avg_min_price)
df['Min.Price']=df['Min.Price'].fillna(avg_min_price)
avg_max_price = np.mean(df['Max.Price'])
print(avg_max_price)
df['Max.Price']=df['Max.Price'].fillna(avg_max_price)
print(df.head())

17.11860465116279
21.45909090909091
  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0

In [52]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)

     0   1   2   3
0   34  36  29  38
1   36  15  25  23
2   22  13  21  34
3   11  25  29  27
4   36  34  33  11
5   37  17  25  17
6   30  30  24  23
7   19  35  37  13
8   21  32  24  18
9   33  14  37  15
10  39  39  35  15
11  29  22  37  36
12  16  20  35  11
13  10  10  19  22
14  25  26  17  19


In [53]:
df[df.sum(axis=1) > 100]

0   1   2   3
0   34  36  29  38
4   36  34  33  11
6   30  30  24  23
7   19  35  37  13
10  39  39  35  15
11  29  22  37  36