Question 1 - Numpy

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [15]:
import numpy as np
import urllib.request
import ssl

# Create an SSL context that ignores certificate verification
context = ssl._create_unverified_context()

# URL of the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Download the file and read its contents
response = urllib.request.urlopen(url, context=context)
data = response.read().decode("utf-8").splitlines()

# Convert to NumPy array
iris_2d = np.genfromtxt(data, delimiter=",", dtype=float, usecols=[0,1,2,3])

In [16]:
A = iris_2d[1:4]
B = iris_2d[6:9]
print(A)
print(B)
C = np.vstack((A,B))
D = np.hstack((A,B))
print(C)
print(D)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[[4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]
[[4.9 3.  1.4 0.2 4.6 3.4 1.4 0.3]
 [4.7 3.2 1.3 0.2 5.  3.4 1.5 0.2]
 [4.6 3.1 1.5 0.2 4.4 2.9 1.4 0.2]]


In [18]:
intersection_set = np.intersect1d(A,B)
print(intersection_set)

[0.2 1.4 1.5 4.6]


In [23]:
print(A[np.where((A < 5) & (A > 3))])

[4.9 4.7 3.2 4.6 3.1]


In [25]:
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
